---
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

# Registration

Register using this [internal OPUS link](http://samarbeid.fhi.no/sites/1294/_layouts/15/WopiFrame.aspx?sourcedoc={91898DA5-F6FA-4578-8C57-7F516DCF032A}&file=Kurs.xlsx&action=default).

# Upcoming Courses

## Intro to Health Economics

**Date:** Wednesday, 6 March 2019

**Teacher:** Torbjorn.Wisloff@fhi.no, Gunhild.Hagen@fhi.no

**Maximum number of participants:** 50

**Location:** MT6, Utsikten, 7th floor

**Language:** English

## Outcome measures

**Date:** 2019

**Teacher:** Torbjorn.Wisloff@fhi.no, Shilpa.Rao@fhi.no

**Maximum number of participants:** 50

**Location:** TBD

**Language:** English

## [A series of short R modules](/short_r_modules/index.html)

**Introduction to R/RStudio** (Gry) - 31/01/2019, 1200-1300
  
**Introduction to variable types/loading of data** (Bea) - 07/02/2019, 1200-1300
  
**If statements/data selection/NA** (Richard) - 14/02/2019, 1200-1300
  
**WINTER BREAK** - 21/02/2019, 1200-1300
  
**Loops** (Bea) - 28/02/2019, 1200-1300
  
**Functions** (Richard) - 07/03/2019, 1200-1300

**Linear Regression** (Ida) - 14/03/2019, 1200-1300

**Logistic Regression** (Ida) - 21/03/2019, 1200-1300

**Data.table/Merging data** (Richard) - 28/03/2019, 1200-1300

**Missing data** (Guido) - 04/04/2019, 1200-1300

**EASTER BREAK** - 11/04/2019, 1200-1300

**EASTER BREAK** - 18/04/2019

**Graphs (ggplot)** (William - 25/04/2019, 1200-1300

**Mixed Models (lme4)** (Bea) - 02/05/2019, 1200-1300

**Survival analysis** (Katrine) - 09/05/2019, 1200-1300

**17TH OF MAY BREAK** - 16/05/2019, 1200-1300

**Marginal effects** (Guido) - 23/05/2019, 1200-1300

XXXXX**??reshaping long+wide** (??) - 30/05/2019, 1200-1300

XXXXX**??Self-selection/loss to followup** (??) - 30/05/2019, 1200-1300


  
**Date:** 2019. Run for 1 hour every Thursday, 1200-1300

**Teachers:** 

- RichardAubrey.White@fhi.no
- Beatriz.ValcarcelSalamanca@fhi.no
- GryMarysol.Groneng@fhi.no
- Ida.Laake@fhi.no
- KatrineDamgaard.Skyrud@fhi.no (survival/data.table/merging)
- WilliamRobertPaul.Denault@fhi.no (ggplot2)
- Guido.Biele@fhi.no (glm, mixed models, missing data, self-selection loss to followup, marginal effects)

## [Best practices for file organization (written document)](/best_practices_files/index.html)

**Date:** 2019

**Teacher:** RichardAubrey.White@fhi.no

\hline

# Course Resources

[Which statistical method should I use?](/which_stats_method/index.html)

[Longitudinal analysis](/longitudinal_analysis/index.html)

[A series of short R modules (in progress)](/short_r_modules/index.html)

# Finished courses

**Wednesday 14 August 2018, 0930-1500:** [Which statistical method should I use?](/which_stats_method/index.html)

**Friday 1 June 2018, 0930-1500:** [Longitudinal analysis](/longitudinal_analysis/index.html)

**Monday 28 April 2018, 0930-1500:** [Longitudinal analysis](/longitudinal_analysis/index.html)

